---

- block:
  - name: Download Google Chrome DMG
    get_url:
      url: https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
      dest: /tmp/googlechrome.dmg

  - name: Mount the DMG
    command: hdiutil attach /tmp/googlechrome.dmg
    register: dmg_mount_output

  - name: Install Google Chrome
    command: cp -R "/Volumes/Google Chrome/Google Chrome.app" /Applications/

  - name: Unmount the DMG
    command: hdiutil detach "/Volumes/Google Chrome"

  - name: Remove the downloaded DMG file
    file:
      path: /tmp/googlechrome.dmg
      state: absent

  - name: Ensure Google Chrome is in the Applications folder
    stat:
      path: /Applications/Google Chrome.app
    register: chrome_installed

  - name: Display a message if Google Chrome was installed
    debug:
      msg: "Google Chrome was installed successfully."
    when: chrome_installed.stat.exists
  tags: chrome